### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by EIKINAKAYAMA** [EIKINAKAYAMA/chat-space#13]
#IPアドレス
18.178.95.20

**Comment by mo1015** [comment]
中山さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○サイドバーの背景色を修正しましょう**


<img width="331" alt="スクリーンショット 2020-07-02 11 33 18" src="https://user-images.githubusercontent.com/62644781/86309980-f5309580-bc57-11ea-8d70-61e25683ee8a.png">

参考カリキュラム
<img width="840" alt="スクリーンショット 2020-06-25 15 44 57" src="https://user-images.githubusercontent.com/62644781/86310084-29a45180-bc58-11ea-908d-66269b60d023.png">


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by EIKINAKAYAMA** [comment]
修正しました！

**Comment by mo1015** [comment]
再提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※今後実装に関する質問がありましたら、メンターに確認をお願いします！**
